version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:14.11.0
      - image: circleci/postgres:12.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test Suite
          command: npm test
      - store_artifacts:
          path: reports/jest/jest.xml
          prefix: tests
      - store_artifacts:
          path: reports/coverage
          prefix: coverage
      - store_test_results:
          path: reports/jest/jest.xml

    environment:
      DB_TEST_USERNAME: postgres
      DB_TEST_PASSWORD: secret
      DB_TEST_DATABASE: backtalk
      HASH_SECRET: a1b2c3d4e5f6g7h8i9j0
      ACCESS_TOKEN_SECRET: a1b2c3d4e5f6g7h8i9j0
      ACCESS_TOKEN_EXPIRATION: 1d
      REFRESH_TOKEN_SECRET: a1b2c3d4e5f6g7h8i9j0
      REFRESH_TOKEN_EXPIRATION: 7d
      COOKIE_SECRET: a1b2c3d4e5f6g7h8i9j0
